[project]
name = "magika"
version = "0.6.0-dev"
description = "A tool to determine the content type of a file with deep learning"
authors = [
    {author = "Magika Developers", email = "magika-dev@google.com"},
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.12"

dependencies = [
    "click>=8.1.7",
    "onnxruntime>=1.19.0",
    "numpy>=2.1.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]

[tool.uv]
dev-dependencies = [
    "mypy>=1.11.2",
    "ipython>=8.27.0",
    "pytest>=8.3.2",
    "ruff>=0.6.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
