name: JS - tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'js/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'js/**'
      - '.github/workflows/**'

jobs:
  unit-testing:
    strategy:
      matrix:
        node-version: ["18", "20"]
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install dependencies
        working-directory: js
        run: yarn
      - name: Build
        working-directory: js
        run: yarn run build
      - name: Run tests
        working-directory: js
        run: yarn test

