name: pytest
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unittesting:
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        - name: Install poetry
          uses: abatilo/actions-poetry@v2
          with:
            poetry-version: "1.7.1"
        - name: Install the project dependencies
          run: cd magika-python-package && poetry install
        - name: Run the automated tests
          run: cd magika-python-package && poetry run pytest tests -m smoketest