name: Python - test

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'python/**'
      - 'tests_data/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'python/**'
      - 'tests_data/**'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  unit-testing:
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
        os: [ "ubuntu-latest", "macos-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.4.0/install.sh | sh

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        working-directory: python
        run: uv sync --all-extras --dev

      - name: Run ruff check
        working-directory: python
        run: uv run ruff check --verbose

      - name: Run ruff format check
        working-directory: python
        run: uv run ruff format --check --verbose

      - name: Run mypy
        working-directory: python
        run: uv run mypy src/magika tests

      - name: Run tests
        working-directory: python
        run: uv run pytest tests -m "not slow"